name: Hourly Cypress E2E Monitoring

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    -  cron: '0 */6 * * *'  # Every hour
  workflow_dispatch:

jobs:
  cypress-monitoring:
    runs-on: ubuntu-latest

    env:
      E2E_USER_PWD: ${{ secrets.E2E_USER_PWD }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Cypress binary
        id: cypress-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress install
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --e2e
